version: '3'

services:
  database:
    image: postgres:14.6
    volumes:
      # cspell:ignore initdb
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=test
